### ISSUE TITLE
Anonymized DNSCrypt v2 protocol and eSNI

### ISSUE THREAD

**Issue by lrq3000** [DNSCrypt/dnscrypt-protocol#4]
Hello,

I saw that the DNSCrypt v2 protocol intends to provide anonymized DNS requests. On [privacytools.io issues tracker](https://github.com/privacytoolsIO/privacytools.io/issues/1822), someone mentioned that there may still be an issue with the SNI.

Since this is way above of my head, could someone please maybe clarify that issue? Thank you very much in advance :-)

**Comment by jedisct1** [comment]
Browsers still leak websites they are trying to reach due to something called SNI.

This is being addresses in a new protocol called ECHO.

But ECHO is independent from DNSCrypt. This is something that web browsers and web servers have to implement.

ECHO isn't implemented anywhere yet, and the protocol itself is still being finalized.
